/** @file */
#ifndef PP2_MACHINE_STACK_DETAIL_STORE_TABLES_H
#define PP2_MACHINE_STACK_DETAIL_STORE_TABLES_H

#define PP2_STACK_FRAME_STORE_0(P,addr,tag,value) PP2_STACK_FRAME_STORE_0_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_0_0 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_1(P,addr,tag,value) PP2_STACK_FRAME_STORE_1_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_1_1 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_2(P,addr,tag,value) PP2_STACK_FRAME_STORE_2_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_2_2 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_3(P,addr,tag,value) PP2_STACK_FRAME_STORE_3_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_3_3 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_4(P,addr,tag,value) PP2_STACK_FRAME_STORE_4_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_4_4 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_5(P,addr,tag,value) PP2_STACK_FRAME_STORE_5_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_5_5 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_6(P,addr,tag,value) PP2_STACK_FRAME_STORE_6_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_6_6 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_7(P,addr,tag,value) PP2_STACK_FRAME_STORE_7_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_7_7 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_8(P,addr,tag,value) PP2_STACK_FRAME_STORE_8_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_8_8 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_9(P,addr,tag,value) PP2_STACK_FRAME_STORE_9_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_9_9 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_10(P,addr,tag,value) PP2_STACK_FRAME_STORE_10_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_10_10 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_11(P,addr,tag,value) PP2_STACK_FRAME_STORE_11_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_11_11 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_12(P,addr,tag,value) PP2_STACK_FRAME_STORE_12_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_12_12 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_13(P,addr,tag,value) PP2_STACK_FRAME_STORE_13_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_13_13 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_14(P,addr,tag,value) PP2_STACK_FRAME_STORE_14_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_14_14 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_15(P,addr,tag,value) PP2_STACK_FRAME_STORE_15_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_15_15 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_16(P,addr,tag,value) PP2_STACK_FRAME_STORE_16_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_16_16 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_17(P,addr,tag,value) PP2_STACK_FRAME_STORE_17_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_17_17 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_18(P,addr,tag,value) PP2_STACK_FRAME_STORE_18_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_18_18 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_19(P,addr,tag,value) PP2_STACK_FRAME_STORE_19_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_19_19 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_20(P,addr,tag,value) PP2_STACK_FRAME_STORE_20_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_20_20 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_21(P,addr,tag,value) PP2_STACK_FRAME_STORE_21_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_21_21 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_22(P,addr,tag,value) PP2_STACK_FRAME_STORE_22_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_22_22 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_23(P,addr,tag,value) PP2_STACK_FRAME_STORE_23_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_23_23 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_24(P,addr,tag,value) PP2_STACK_FRAME_STORE_24_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_24_24 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_25(P,addr,tag,value) PP2_STACK_FRAME_STORE_25_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_25_25 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_26(P,addr,tag,value) PP2_STACK_FRAME_STORE_26_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_26_26 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_27(P,addr,tag,value) PP2_STACK_FRAME_STORE_27_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_27_27 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_28(P,addr,tag,value) PP2_STACK_FRAME_STORE_28_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_28_28 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_29(P,addr,tag,value) PP2_STACK_FRAME_STORE_29_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_29_29 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_30(P,addr,tag,value) PP2_STACK_FRAME_STORE_30_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_30_30 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_31(P,addr,tag,value) PP2_STACK_FRAME_STORE_31_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_31_31 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_32(P,addr,tag,value) PP2_STACK_FRAME_STORE_32_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_32_32 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_33(P,addr,tag,value) PP2_STACK_FRAME_STORE_33_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_33_33 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_34(P,addr,tag,value) PP2_STACK_FRAME_STORE_34_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_34_34 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_35(P,addr,tag,value) PP2_STACK_FRAME_STORE_35_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_35_35 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_36(P,addr,tag,value) PP2_STACK_FRAME_STORE_36_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_36_36 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_37(P,addr,tag,value) PP2_STACK_FRAME_STORE_37_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_37_37 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_38(P,addr,tag,value) PP2_STACK_FRAME_STORE_38_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_38_38 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_39(P,addr,tag,value) PP2_STACK_FRAME_STORE_39_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_39_39 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_40(P,addr,tag,value) PP2_STACK_FRAME_STORE_40_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_40_40 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_41(P,addr,tag,value) PP2_STACK_FRAME_STORE_41_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_41_41 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_42(P,addr,tag,value) PP2_STACK_FRAME_STORE_42_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_42_42 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_43(P,addr,tag,value) PP2_STACK_FRAME_STORE_43_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_43_43 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_44(P,addr,tag,value) PP2_STACK_FRAME_STORE_44_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_44_44 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_45(P,addr,tag,value) PP2_STACK_FRAME_STORE_45_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_45_45 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_46(P,addr,tag,value) PP2_STACK_FRAME_STORE_46_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_46_46 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_47(P,addr,tag,value) PP2_STACK_FRAME_STORE_47_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_47_47 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_48(P,addr,tag,value) PP2_STACK_FRAME_STORE_48_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_48_48 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_49(P,addr,tag,value) PP2_STACK_FRAME_STORE_49_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_49_49 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_50(P,addr,tag,value) PP2_STACK_FRAME_STORE_50_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_50_50 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_51(P,addr,tag,value) PP2_STACK_FRAME_STORE_51_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_51_51 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_52(P,addr,tag,value) PP2_STACK_FRAME_STORE_52_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_52_52 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_53(P,addr,tag,value) PP2_STACK_FRAME_STORE_53_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_53_53 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_54(P,addr,tag,value) PP2_STACK_FRAME_STORE_54_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_54_54 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_55(P,addr,tag,value) PP2_STACK_FRAME_STORE_55_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_55_55 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_56(P,addr,tag,value) PP2_STACK_FRAME_STORE_56_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_56_56 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_57(P,addr,tag,value) PP2_STACK_FRAME_STORE_57_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_57_57 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_58(P,addr,tag,value) PP2_STACK_FRAME_STORE_58_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_58_58 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_59(P,addr,tag,value) PP2_STACK_FRAME_STORE_59_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_59_59 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_60(P,addr,tag,value) PP2_STACK_FRAME_STORE_60_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_60_60 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_61(P,addr,tag,value) PP2_STACK_FRAME_STORE_61_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_61_61 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_62(P,addr,tag,value) PP2_STACK_FRAME_STORE_62_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_62_62 ,PP2_STACK_FRAME_STORE_BREAK

#define PP2_STACK_FRAME_STORE_63(P,addr,tag,value) PP2_STACK_FRAME_STORE_63_##addr,PP2_STACK_FRAME_STORE_CONTINUE,P##addr,P##tag,P##value,
#define PP2_STACK_FRAME_STORE_63_63 ,PP2_STACK_FRAME_STORE_BREAK

#endif