name: 'build-and-publish-docs'
description: ''
inputs:
    input-branch:
        description: ''
        required: true
        default: 'master'
    output-branch:
        description: ''
        required: true
        default: 'gh-pages'
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.input-branch }}
        - ${{ inputs.output-branch }}