/** @file */
#ifndef PP2_PRIMITIVE_INTROSPECTION_IS_TUPLE_H
#define PP2_PRIMITIVE_INTROSPECTION_IS_TUPLE_H

#define PP2_IS_TUPLE(x) IP2_IS_TUPLE_TEST_I(IP2_IS_TUPLE_TEST_II x,0)
#define IP2_IS_TUPLE_TEST_I(...) IP2_IS_TUPLE_TEST_III(__VA_ARGS__)
#define IP2_IS_TUPLE_TEST_II(...) ,1
#define IP2_IS_TUPLE_TEST_III(_,x,...) x

#endif