name: Build and Publish Documentation

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build-and-publish-docs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Execute
        uses: ./.github/actions/build-and-publish-docs
     
